### PR TITLE
Publish story bug fix

### PR DESCRIPTION
**Pull request by marcokumu**
Fixes issue #340  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

# Screenshot 

Screenshot from 2023-03-09 20-35-38

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by LemmyMwaura — APPROVED** [review]

**Review by LemmyMwaura — CHANGES_REQUESTED** [review]
You've reverted the mat-stepper changes. Please fix that

**Comment by marcokumu** [comment]
> You've reverted the mat-stepper changes. Please fix that

I've fixed the issue

**Comment by LemmyMwaura** [comment]
@marcokumu your develop branch was not up to date This will break a lot of features

**Comment by marcokumu** [comment]
I've open another PR

**Pull request closed without merging**
