### PR TITLE
🎨 Redesign Login Page

### PR DESCRIPTION
**Pull request by SnowJunior**
# Description
This is the redesign of the login screen 

Fixes # (issue) - #480 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

Screenshot from 2023-05-17 15-47-16

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SnowJunior** [comment]
@LemmyMwaura awaitong review

**Comment by SnowJunior** [comment]
@LemmyMwaura

**Review by LemmyMwaura — CHANGES_REQUESTED** [review]
Almost there, make it responsive at a minimum of 370px.

**Comment by SnowJunior** [comment]
the whole page or just the button
@LemmyMwaura

**Comment by LemmyMwaura** [comment]
Closing this in favour of #480

**Pull request closed without merging**
