### PR TITLE
:art: Rework Block List UI

### LINKED ISSUE #357: 🎨 Rework Block List UI
```markdown
**As a user of the CLM block list feature,
**I want the UI design to match the provided designs so that it is visually consistent with the rest of the application.

Scattering information in emails and other places makes it difficult to work collaboratively,
so I need all the relevant information within the relevant issue.

### Description

The current UI design of the block list does not match the designs provided in the design specification document. The spacing between the blocks is inconsistent and the font size and icons are not the same as in the designs. 

Therefore, we need to rework the UI design of the block list to match the provided designs. The spacing between the blocks should be consistent and clearly defined, and the font size and icons should match the designs. This will ensure that the feature is visually consistent with the rest of the application and is visually appealing to use for the users.


### Acceptance Criteria

1. The spacing between the blocks is consistent and clearly defined, with appropriate margins and paddings.
2. The font size and icons match the designs provided, with appropriate contrast and readability.
3. The UI design is visually consistent with the rest of the application, with appropriate colors, icons, and styles.

Please also note:

1. If a conversation about the issue I’m working on is happening,
the outcomes should be documented within that issue (not in the comments).


```
### Design to be implemented 👍🏽 

Screenshot 2023-03-15 at 12 05 45

### PR DESCRIPTION
**Pull request by Michael-Otieno**
# Description

I worked alone.

This pull request solves issue #357, whereby I have redesigned the Block List UI following the design's guidelines.

Fixes #357

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

https://user-images.githubusercontent.com/85155606/232036914-31dc1ff3-182c-44ef-9ffe-112f6be9e5ab.mp4

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
-  [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Michael-Otieno** [comment]
The icons are premium.  Waiting for Review @LemmyMwaura

**Review by LemmyMwaura — CHANGES_REQUESTED** [review]
Good job on the design however the functionality can be cleaned up a bit.Add a property to uniquely identify the different types of blocks and use that to filter them depending on their type. That will be a much cleaner approach.

**Comment by Michael-Otieno** [comment]
> Good job on the design however the functionality can be cleaned up a bit.Add a property to uniquely identify the different types of blocks and use that to filter them depending on their type. That will be a much cleaner approach.

Done. Waiting for Review @LemmyMwaura

**Review by LemmyMwaura — APPROVED** [review]
Good Job 👍

**Pull request merged**
