### PR TITLE
🎨 CLM-369 Bots (Main, Modules, Lessons) Page(s) Design Cleanup

### LINKED ISSUE #888: 🎨  CLM-369 Bots (Main, Modules, Lessons) Page(s) Design Cleanup
### Main Page

1. Bots Page Title

- Set page title font-size to 2rem, font-weight to 400, and margin-top to -10px.

2. Date Created and View All functions should not have a joined background.

Screenshot 2023-11-24 at 12 57 20

3. Search Function

- Remove the white background from the search input field.

- Adjust the search icon to face the opposite direction.

- Lighten the font-weight of 'Search for a Course' (font-weight: 300).

 4. Table Row Hover Effect

- Implement a hover effect on table data with background-color: #1F7A8C and 40% opacity not as it is currently.

Screenshot 2023-11-24 at 12 42 52

### Modules Page

1. Title - Module page title should have font-size: 2rem, font-weight: 400, margin-top: -10px.

2. Search function

Screenshot 2023-11-24 at 13 00 32

- The icon is out of the search input field

- Make the icon face the opposite direction

- Reduce the font weight to 300

3. Module card

Screenshot 2023-11-24 at 13 03 52

- Align the module name (in this case ‘demo module’) horizontally with the menu icon

### Lessons Page

1.  Title - Lessons page title should have font-size: 2rem, font-weight: 400, margin-top: -10px.

2. Search function

- The icon is out of the search input field

- Make the icon face the opposite direction

- Reduce the font-weight to 300

3. Lesson card

- Align the module name horizontally with the menu icon

### PR DESCRIPTION
**Pull request by darlene9497**
# Description

Main Page:
Bots Page Title:
Set page title font-size to 2rem, font-weight to 400, and margin-top to -10px.
Screenshot from 2023-12-06 15-18-55

Align title to main title
Screenshot from 2023-12-06 15-04-31

Date Created and View All:
Ensured that Date Created and View All functions do not have a joined background
Screenshot from 2023-12-01 16-11-19

Search Function:
Removed the white background from the search input field.
Adjusted the search icon to face the opposite direction.
Lightened the font-weight of 'Search for a Course' to 300.
Removed filter box-shadow.
Screenshot from 2023-12-06 15-25-30

Table Row Hover Effect:
Implemented a hover effect on table data with background-color: #1F7A8C and 40% opacity.
Screenshot from 2023-12-01 19-54-07

Modules Page:
Title:
Modules page title now has a font-size of 2rem, font-weight of 400, and margin-top of -10px.

Search Function:
The icon is now inside the search input field.
Screenshot from 2023-12-04 10-08-48
The search icon faces the opposite direction.
Reduced the font weight to 300.

Module Card:
Aligned the module name horizontally with the menu icon.
Aligned title with tooltip.
Added padding (left and right) to card items.
Screenshot from 2023-12-06 16-05-29

Lessons Page:
Title:
Lessons page title has a font-size of 2rem, font-weight of 400, and margin-top of -10px.

Search Function:
The icon is now inside the search input field.
Screenshot from 2023-12-04 10-18-16
The search icon faces the opposite direction.
Reduced the font-weight to 300.

Lesson Card:
Aligned the module name horizontally with the menu icon.
Aligned title with tooltip.
Added padding (left and right) to card items.
Screenshot from 2023-12-06 16-25-24

Fixes #888.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by LemmyMwaura — CHANGES_REQUESTED** [review]
Align the bots title with the main title by adjusting the padding. Should look like surveys. 

Screenshot 2023-12-06 at 12 23 18
Screenshot 2023-12-06 at 12 23 03

Remove box shadow from filter.

Screenshot 2023-12-06 at 12 23 48

Alight title with tooltip.
Add padding (left and right) to card items. 

Screenshot 2023-12-06 at 12 26 43


Screenshot 2023-12-06 at 12 26 51

**Review by LemmyMwaura — CHANGES_REQUESTED** [review]
The lessons card and the modules card don't have a similar design. Also kindly edit the search in the main bots page to match the one in the all bots page with the search inside the input field.

**Comment by darlene9497** [comment]
Screenshot from 2023-12-13 12-56-33
In regards to lessons card and the modules card not having a similar design, what do you mean?

**Comment by LemmyMwaura** [comment]
> Screenshot from 2023-12-13 12-56-33 @LemmyMwaura In regards to the lessons card and the modules card not having a similar design, what do you mean?

Same padding. The width of both cards should be similar.

**Review by LemmyMwaura — APPROVED** [review]

**Pull request merged**
