### PR TITLE
Ft conditional block

### PR DESCRIPTION
**Pull request by njugunaemilly**
I have made requested changes.

### CODE REVIEW

**Comment by LemmyMwaura** [comment]
@njugunaemilly kindly link the previous PR i had reviewed and also sync the latest changes and resolve conflicts

**Comment by njugunaemilly** [comment]
@LemmyMwaura this resolves changes requested for #742

**Comment by LemmyMwaura** [comment]
> I have made requested changes.

Use our PR template kindly

**Comment by njugunaemilly** [comment]
# Description
This PR redesigns the conditional block to achieve a better UI experience.

Fixes #636 

# Screenshot (optional)

image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

**Comment by LemmyMwaura** [comment]
Closing this as it's been resolved.

**Pull request closed without merging**
