### PR TITLE
✨ 📺 CLM-332 Implement Channels State Layer

### PR DESCRIPTION
**Pull request by LemmyMwaura**
# Description

This PR adds the channel state layer and cleansup the surveys and message-template data stores.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by ReaganCn — CHANGES_REQUESTED** [review]
@LemmyMwaura I dont see the integration with frontend - Japheth's implementation. I should be able to manage channels from the frontend

**Comment by LemmyMwaura** [comment]
@ReaganCn This is just the state layer. He has to pull it after merging and then integrate it on his end.

**Comment by ReaganCn** [comment]
You are the one who was to integrate it, from his changes so that I could review one combined PR

**Comment by LemmyMwaura** [comment]
I'll integrate it on his branch after this is merged.

**Review by ReaganCn — APPROVED** [review]

**Pull request merged**
