### PR TITLE
:lipstick: feat: CLM 322 collapse chats and templates sub menu into messaging #787

### LINKED ISSUE #787: 🎨💄 CLM-322Collapse Chats and Templates sub-menu into Messaging
### User Stories

The Messaging menu is not clickable at the moment. Also, the Chats and Message Templates appear out of alignment when the menu is collapsed. 
We should therefore nest them under Messaging, and then when this is clicked the menu opens and the two are visible. 

###Technical Description 
The page currently has this design
### Current design

Screenshot from 2023-11-01 08-44-12

## Assets
angle-small-down

it should be changed to this design
### Required design

image-20231031-115905

The file to edit is in this  path `libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html`
### Acceptance Criteria

1.The default behaviour of the menu should be that Chats and Message Templates are nested under the Messaging parent. 

2.When the user clicks on Messaging the menu should open and Chats and Message Templates are then visible so the user can navigate wherever they wish.
3.Do not change the icons. Only add the drop down.

### PR DESCRIPTION
**Pull request by thadeusdev**
# Description

- Clm 322 collapse chats and templates sub menu into messaging

Fixes #787

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
down
up

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by paulkahura** [comment]
Kindly make the icon smaller

**Comment by thadeusdev** [comment]
noted. thank you so much

**Comment by thadeusdev** [comment]
I've made the requested adjustments to our svg toggle icon

**Review by LemmyMwaura — APPROVED** [review]

**Comment by LemmyMwaura** [comment]
I've reverted the PR not cause it's not clean but because of the extra indentations. Kindly prevent auto indenting on save

**Comment by thadeusdev** [comment]
Noted. Thank you for the heads up

**Comment by LemmyMwaura** [comment]
@thadeusdev it's not completely resolved so you can create another PR without the indentation.

**Comment by thadeusdev** [comment]
Hi @LemmyMwaura I have created another fully functional PR of this issue #827  as requested. Thank you once more

**Pull request merged**
