### PR TITLE
:lipstick:Location input block

### PR DESCRIPTION
**Pull request by Dancunrandy**
Re-designed the Location input block
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)
Screenshot from 2023-11-05 13-49-43
Screenshot from 2023-11-05 13-49-53

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Dancunrandy** [comment]
@LemmyMwaura , ignore the previous input block, i created a new one

**Comment by LemmyMwaura** [comment]
> @LemmyMwaura , ignore the previous input block PR, i created a new one

You mean this one? or which is previous.

**Comment by Dancunrandy** [comment]
@LemmyMwaura , yeah..if if you check the closed PR you will see it, i closed it by mistake

**Comment by Dancunrandy** [comment]
@LemmyMwaura , Ignore this one

**Pull request closed without merging**
