### PR TITLE
🎨💄 CLM-322 Collapse Chats and Templates sub-menu into Messaging #787

### LINKED ISSUE #787: 🎨💄 CLM-322Collapse Chats and Templates sub-menu into Messaging
### User Stories

The Messaging menu is not clickable at the moment. Also, the Chats and Message Templates appear out of alignment when the menu is collapsed. 
We should therefore nest them under Messaging, and then when this is clicked the menu opens and the two are visible. 

###Technical Description 
The page currently has this design
### Current design

Screenshot from 2023-11-01 08-44-12

## Assets
angle-small-down

it should be changed to this design
### Required design

image-20231031-115905

The file to edit is in this  path `libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html`
### Acceptance Criteria

1.The default behaviour of the menu should be that Chats and Message Templates are nested under the Messaging parent. 

2.When the user clicks on Messaging the menu should open and Chats and Message Templates are then visible so the user can navigate wherever they wish.
3.Do not change the icons. Only add the drop down.

### PR DESCRIPTION
**Pull request by Mutagah**
# Description

Makes UI changes to the side-menu that would be more visually appealing.

Fixes #787 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

https://github.com/italanta/elewa/assets/106149210/a09d372f-943e-42dd-9499-d87eb3845798

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by LemmyMwaura — CHANGES_REQUESTED** [review]
Kindly update the menu toggle icons with those on the design

**Comment by Mutagah** [comment]
> Kindly update the menu toggle icons with those on the design

No toggle icons were provided.

**Comment by Mutagah** [comment]
> > > Kindly update the menu toggle icons with those on the design
> > 
> > 
> > No toggle icons were provided.
> 
> Okay, I'll update the issue with a link to the new icons, be on the lookout.

Requested changes have been addressed.

**Comment by Mutagah** [comment]
The issue that this PR is supposed to fix has been solved

**Pull request closed without merging**
