### PR TITLE
🎨 Block redesign  location input block #621

### LINKED ISSUE #621: :art: Block Redesign: Location Input Block
## User stories

As a user I'd prefer the second designs to the first.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Technical Description
The current design is: 
image

It should be changed to:
image

The files can be found at `libs/features/convs-mgr/stories/blocks/library/location-message-block/`. 

The designs are [here](https://www.figma.com/file/ZGHzSstXOYPMFU1EiqjEHD/Untitled?type=design&node-id=1%3A4&mode=design&t=Hf7DxaUUMQ3BWy57-1)

### Acceptance Criteria

1. The block should look exactly like the designs.
2. Use of `rem`, `em` as opposed to `px`.

### PR DESCRIPTION
**Pull request by Tracie35**
# Description
This PR makes UI changes to location input block

Fixes #621 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)

s

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by LemmyMwaura — CHANGES_REQUESTED** [review]
The design changes have been made on the wrong block. Should be implemented on location-input block

**Comment by Tracie35** [comment]
@LemmyMwaura 
I've made the changes you requested

**Comment by LemmyMwaura** [comment]
@Tracie35 sync changes then and check to make sure the design is Okay.

**Comment by Tracie35** [comment]
@LemmyMwaura made changes you requested

**Review by LemmyMwaura — APPROVED** [review]

**Pull request merged**
