### PR TITLE
:art:  App Design: Sign up Page

### LINKED ISSUE #383: 🎨  App Design: Sign up Page
#  App Design: Sign up Page
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to Sign up to use the application with my credentials or use a google sign up.

### Description

The current sign up page is as shown below:
image

On scroll:
image

The page needs to be updated to appear as shown below:
Screenshot 2022-11-08 at 12 32 44

Your assignment is to redesign the page to appear as above.

When a user clicks on the "Create Account" Button, the text should change to "Please wait..." with a material spinner next to it. The text fields on the page should also be disabled when saving the user.
### Technical Analysis

This feature can be found in libs/features/app/auth/register. 

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.

### PR DESCRIPTION
**Pull request by Michael-Otieno**
# Description

I worked alone.

This pull request solves issue #383, whereby I have redesigned the Signup Page following the design's guidelines.

Fixes #383

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Screenshot (optional)
https://user-images.githubusercontent.com/85155606/229223529-23c4fa4d-45b9-4807-8bec-0b75b3ce8e8d.mp4

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
-  [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Michael-Otieno** [comment]
Waiting for review @LemmyMwaura

**Comment by Michael-Otieno** [comment]
> Good work. Please share a video on scrolling of the signup page. It was cutting out on the bottom when scrolling(screenshot on the issue description).
The page doesn't scroll. It's one page covering the whole screed

**Comment by Michael-Otieno** [comment]
> Good work. Please share a video on scrolling of the signup page. It was cutting out on the bottom when scrolling(screenshot on the issue description).

The page has no scroll. It covers the whole screen with no scroll @ReaganCn

**Review by ReaganCn — APPROVED** [review]

**Comment by ReaganCn** [comment]
Also there was no need to update these. This issue was design only.
image

**Review by ReaganCn — CHANGES_REQUESTED** [review]
Also there was no need to update these. This issue was design only.
image

**Review by ReaganCn — APPROVED** [review]

**Comment by ReaganCn** [comment]
@Michael-Otieno Are you in the Moringa slack channel. What is your handle?

**Pull request merged**
